//! The bodies of the modded configuration tasks after the resource pack.
//!
//! They are the bodies that the `NeoForge` [`EMULATED_NEOFORGE_VERSION`] server sends. The tables
//! come from run (b) of
//! `tools/pumpkin-neoforge-client/captures/neoforge-26.3.0.64-beta/` and change only with the
//! emulated version.
//!
//! `neoforge-synced.toml`, `NeoForge`'s own synced config, is the file
//! `assets/neoforge/neoforge-synced.toml` in the repository root: the 1168 bytes of the
//! `neoforge:config_file` payload of run (b), captured from the real server, not generated by
//! `IronPumpkin`.

use pumpkin_protocol::java::neoforge::{
    ConfigFilePayload, EnumEntry, ExtensibleEnumDataPayload, KnownDataMap,
    KnownRegistryDataMapsPayload, NetworkCheck,
};
use pumpkin_util::{identifier::Identifier, text::TextComponent};

#[cfg(doc)]
use super::neoforge::EMULATED_NEOFORGE_VERSION;
use crate::plugin::startup::SyncedConfig;

/// The file name of `NeoForge`'s own synced config (`NeoForgeMod`'s `ModConfig.Type.SYNCED`).
pub const NEOFORGE_SYNCED_CONFIG_NAME: &str = "neoforge-synced.toml";

/// The contents of `NeoForge`'s own synced config.
pub static NEOFORGE_SYNCED_CONFIG: &[u8] =
    include_bytes!("../../../../../assets/neoforge/neoforge-synced.toml");

/// `NetworkRegistry.SUPPORTED_COMMON_NETWORKING_VERSIONS`.
pub const SUPPORTED_COMMON_NETWORKING_VERSIONS: [i32; 1] = [1];

/// The data maps of `RegistryManager.getDataMaps()` that have a network codec, per registry, in
/// the `HashMap` order of run (b). None is `mandatorySync`.
const KNOWN_DATA_MAPS: [(&str, &[&str]); 7] = [
    (
        "minecraft:block",
        &[
            "neoforge:transformables",
            "neoforge:oxidizables",
            "neoforge:waxables",
        ],
    ),
    ("minecraft:item", &[]),
    (
        "minecraft:entity_type",
        &[
            "neoforge:acceptable_villager_distances",
            "neoforge:monster_room_mobs",
            "neoforge:parrot_imitations",
        ],
    ),
    ("minecraft:worldgen/biome", &["neoforge:villager_types"]),
    ("minecraft:game_event", &["neoforge:vibration_frequencies"]),
    (
        "minecraft:villager_profession",
        &["neoforge:raid_hero_gifts"],
    ),
    (
        "minecraft:block_transformer",
        &["neoforge:block_transform_appenders"],
    ),
];

/// The networked extensible enums of `CheckExtensibleEnums`, in the `HashMap` order of run (b).
/// No mod extends them, so no entry has extension data.
const EXTENSIBLE_ENUMS: [(&str, NetworkCheck); 9] = [
    (
        "net.minecraft.world.item.ItemUseAnimation",
        NetworkCheck::Bidirectional,
    ),
    (
        "net.minecraft.world.damagesource.DamageScaling",
        NetworkCheck::Clientbound,
    ),
    (
        "net.minecraft.world.item.component.FireworkExplosion$Shape",
        NetworkCheck::Bidirectional,
    ),
    (
        "net.minecraft.world.level.biome.BiomeSpecialEffects$GrassColorModifier",
        NetworkCheck::Clientbound,
    ),
    (
        "net.minecraft.world.damagesource.DamageEffects",
        NetworkCheck::Clientbound,
    ),
    (
        "net.minecraft.world.damagesource.DeathMessageType",
        NetworkCheck::Clientbound,
    ),
    (
        "net.minecraft.world.inventory.RecipeBookType",
        NetworkCheck::Clientbound,
    ),
    (
        "net.minecraft.world.item.ItemDisplayContext",
        NetworkCheck::Clientbound,
    ),
    (
        "net.minecraft.world.item.Rarity",
        NetworkCheck::Bidirectional,
    ),
];

/// `RegistryDataMapNegotiation.run` for a `NeoForge` connection.
#[must_use]
pub fn known_registry_data_maps() -> KnownRegistryDataMapsPayload {
    KnownRegistryDataMapsPayload {
        data_maps: KNOWN_DATA_MAPS
            .iter()
            .map(|&(registry, maps)| {
                let maps = maps
                    .iter()
                    .map(|&id| KnownDataMap {
                        id: Identifier::parse_static(id),
                        mandatory: false,
                    })
                    .collect();
                (Identifier::parse_static(registry), maps)
            })
            .collect(),
    }
}

/// `CheckExtensibleEnums.start` for a `NeoForge` connection.
#[must_use]
pub fn extensible_enum_data() -> ExtensibleEnumDataPayload {
    ExtensibleEnumDataPayload {
        enum_entries: EXTENSIBLE_ENUMS
            .iter()
            .map(|&(class_name, network_check)| {
                (
                    class_name.to_owned(),
                    EnumEntry {
                        class_name: class_name.to_owned(),
                        network_check,
                        data: None,
                    },
                )
            })
            .collect(),
    }
}

/// `ConfigSync.syncAllConfigs`: `NeoForge`'s own synced config, then the synced configs of the
/// native mods in mod id order.
#[must_use]
pub fn config_files(mod_configs: &[SyncedConfig]) -> Vec<ConfigFilePayload> {
    std::iter::once(ConfigFilePayload {
        file_name: NEOFORGE_SYNCED_CONFIG_NAME.to_owned(),
        contents: NEOFORGE_SYNCED_CONFIG.into(),
    })
    .chain(mod_configs.iter().map(|config| ConfigFilePayload {
        file_name: config.file_name.clone(),
        contents: config.contents.clone(),
    }))
    .collect()
}

/// The reason of `NetworkRegistry.checkCommonVersion` when the client has no supported version.
/// `NeoForge` sends a literal, not a translation.
#[must_use]
pub fn unsupported_common_version() -> TextComponent {
    let versions: Vec<String> = SUPPORTED_COMMON_NETWORKING_VERSIONS
        .iter()
        .map(ToString::to_string)
        .collect();
    TextComponent::text(format!(
        "Unsupported common network version. This installation of NeoForge only supports: {}",
        versions.join(", ")
    ))
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A capture fixture of the protocol crate: hex digits, surrounding whitespace ignored.
    fn hex_fixture(text: &str) -> Vec<u8> {
        hex::decode(text.trim()).unwrap()
    }

    #[test]
    fn data_maps_equal_the_captured_payload() {
        let mut bytes = Vec::new();
        known_registry_data_maps().write(&mut bytes).unwrap();
        let captured = hex_fixture(include_str!(
            "../../../../pumpkin-protocol/src/java/neoforge/fixtures/run-b-known-registry-data-maps.hex"
        ));
        assert_eq!(bytes, captured);
        let payload = known_registry_data_maps();
        assert_eq!(payload.data_maps.len(), 7);
        assert_eq!(payload.data_maps.values().map(Vec::len).sum::<usize>(), 10);
        assert!(
            payload
                .data_maps
                .values()
                .flatten()
                .all(|map| !map.mandatory)
        );
    }

    #[test]
    fn enum_entries_equal_the_captured_payload() {
        let mut bytes = Vec::new();
        extensible_enum_data().write(&mut bytes).unwrap();
        let captured = hex_fixture(include_str!(
            "../../../../pumpkin-protocol/src/java/neoforge/fixtures/run-b-extensible-enum-data.hex"
        ));
        assert_eq!(bytes, captured);
        let payload = extensible_enum_data();
        assert_eq!(payload.enum_entries.len(), 9);
        assert!(
            payload
                .enum_entries
                .values()
                .all(|entry| entry.data.is_none())
        );
    }

    #[test]
    fn neoforge_config_is_the_captured_file() {
        assert_eq!(NEOFORGE_SYNCED_CONFIG.len(), 1168);
        let text = std::str::from_utf8(NEOFORGE_SYNCED_CONFIG).unwrap();
        assert!(text.contains("permissionHandler = \"neoforge:default_handler\""));
        assert_eq!(
            config_files(&[]),
            [ConfigFilePayload {
                file_name: NEOFORGE_SYNCED_CONFIG_NAME.to_owned(),
                contents: NEOFORGE_SYNCED_CONFIG.into(),
            }]
        );
    }

    #[test]
    fn mod_configs_follow_the_neoforge_config() {
        let config = SyncedConfig {
            file_name: "testmod-server.toml".to_owned(),
            contents: b"enabled = 1\n".as_slice().into(),
        };
        let files = config_files(std::slice::from_ref(&config));
        let names: Vec<&str> = files.iter().map(|file| file.file_name.as_str()).collect();
        assert_eq!(names, [NEOFORGE_SYNCED_CONFIG_NAME, "testmod-server.toml"]);
        assert_eq!(files[1].contents, config.contents);
    }

    #[test]
    fn the_version_kick_lists_the_supported_versions() {
        assert_eq!(
            unsupported_common_version().get_text(),
            "Unsupported common network version. This installation of NeoForge only supports: 1"
        );
    }
}
