#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum StructurePieceType {
    // Mineshaft
    MineshaftCorridor,
    MineshaftCrossing,
    MineshaftRoom,
    MineshaftStairs,

    // Nether Fortress
    NetherFortressBridgeCrossing,
    NetherFortressBridgeEnd,
    NetherFortressBridge,
    NetherFortressCorridorStairs,
    NetherFortressCorridorBalcony,
    NetherFortressCorridorExit,
    NetherFortressCorridorCrossing,
    NetherFortressCorridorLeftTurn,
    NetherFortressSmallCorridor,
    NetherFortressCorridorRightTurn,
    NetherFortressCorridorNetherWartsRoom,
    NetherFortressBridgePlatform,
    NetherFortressBridgeSmallCrossing,
    NetherFortressBridgeStairs,
    NetherFortressStart,

    // Stronghold
    StrongholdChestCorridor,
    StrongholdSmallCorridor,
    StrongholdFiveWayCrossing,
    StrongholdLeftTurn,
    StrongholdLibrary,
    StrongholdPortalRoom,
    StrongholdPrisonHall,
    StrongholdRightTurn,
    StrongholdSquareRoom,
    StrongholdSpiralStaircase,
    StrongholdStart,
    StrongholdCorridor,
    StrongholdStairs,

    // Overworld/General
    JungleTemple,
    OceanTemple,
    Igloo,
    RuinedPortal,
    SwampHut,
    DesertTemple,

    // Ocean Monument
    OceanMonumentBase,
    OceanMonumentCoreRoom,
    OceanMonumentDoubleXRoom,
    OceanMonumentDoubleXYRoom,
    OceanMonumentDoubleYRoom,
    OceanMonumentDoubleYZRoom,
    OceanMonumentDoubleZRoom,
    OceanMonumentEntryRoom,
    OceanMonumentPenthouse,
    OceanMonumentSimpleRoom,
    OceanMonumentSimpleTopRoom,
    OceanMonumentWingRoom,

    // End / Other
    EndCity,
    WoodlandMansion,
    BuriedTreasure,
    Shipwreck,
    NetherFossil,
    Jigsaw,
}

impl StructurePieceType {
    /// The key of this piece type in the vanilla `structure_piece` registry, as
    /// `StructurePiece.createTag` writes it under `id`.
    #[must_use]
    pub const fn id(&self) -> &'static str {
        match self {
            Self::MineshaftCorridor => "minecraft:mscorridor",
            Self::MineshaftCrossing => "minecraft:mscrossing",
            Self::MineshaftRoom => "minecraft:msroom",
            Self::MineshaftStairs => "minecraft:msstairs",
            Self::NetherFortressBridgeCrossing => "minecraft:nebcr",
            Self::NetherFortressBridgeEnd => "minecraft:nebef",
            Self::NetherFortressBridge => "minecraft:nebs",
            Self::NetherFortressCorridorStairs => "minecraft:neccs",
            Self::NetherFortressCorridorBalcony => "minecraft:nectb",
            Self::NetherFortressCorridorExit => "minecraft:nece",
            Self::NetherFortressCorridorCrossing => "minecraft:nescsc",
            Self::NetherFortressCorridorLeftTurn => "minecraft:nesclt",
            Self::NetherFortressSmallCorridor => "minecraft:nesc",
            Self::NetherFortressCorridorRightTurn => "minecraft:nescrt",
            Self::NetherFortressCorridorNetherWartsRoom => "minecraft:necsr",
            Self::NetherFortressBridgePlatform => "minecraft:nemt",
            Self::NetherFortressBridgeSmallCrossing => "minecraft:nerc",
            Self::NetherFortressBridgeStairs => "minecraft:nesr",
            Self::NetherFortressStart => "minecraft:nestart",
            Self::StrongholdChestCorridor => "minecraft:shcc",
            Self::StrongholdSmallCorridor => "minecraft:shfc",
            Self::StrongholdFiveWayCrossing => "minecraft:sh5c",
            Self::StrongholdLeftTurn => "minecraft:shlt",
            Self::StrongholdLibrary => "minecraft:shli",
            Self::StrongholdPortalRoom => "minecraft:shpr",
            Self::StrongholdPrisonHall => "minecraft:shph",
            Self::StrongholdRightTurn => "minecraft:shrt",
            Self::StrongholdSquareRoom => "minecraft:shrc",
            Self::StrongholdSpiralStaircase => "minecraft:shsd",
            Self::StrongholdStart => "minecraft:shstart",
            Self::StrongholdCorridor => "minecraft:shs",
            Self::StrongholdStairs => "minecraft:shssd",
            Self::JungleTemple => "minecraft:tejp",
            Self::OceanTemple => "minecraft:orp",
            Self::Igloo => "minecraft:iglu",
            Self::RuinedPortal => "minecraft:rupo",
            Self::SwampHut => "minecraft:tesh",
            Self::DesertTemple => "minecraft:tedp",
            Self::OceanMonumentBase => "minecraft:omb",
            Self::OceanMonumentCoreRoom => "minecraft:omcr",
            Self::OceanMonumentDoubleXRoom => "minecraft:omdxr",
            Self::OceanMonumentDoubleXYRoom => "minecraft:omdxyr",
            Self::OceanMonumentDoubleYRoom => "minecraft:omdyr",
            Self::OceanMonumentDoubleYZRoom => "minecraft:omdyzr",
            Self::OceanMonumentDoubleZRoom => "minecraft:omdzr",
            Self::OceanMonumentEntryRoom => "minecraft:omentry",
            Self::OceanMonumentPenthouse => "minecraft:ompenthouse",
            Self::OceanMonumentSimpleRoom => "minecraft:omsimple",
            Self::OceanMonumentSimpleTopRoom => "minecraft:omsimplet",
            Self::OceanMonumentWingRoom => "minecraft:omwr",
            Self::EndCity => "minecraft:ecp",
            Self::WoodlandMansion => "minecraft:wmp",
            Self::BuriedTreasure => "minecraft:btp",
            Self::Shipwreck => "minecraft:shipwreck",
            Self::NetherFossil => "minecraft:nefos",
            Self::Jigsaw => "minecraft:jigsaw",
        }
    }
}
